[package]
name = "cherryrgb_cli"
version = "2.2.4"
edition = "2018"
publish = false

[features]
uhid = ["cherryrgb/uhid"]

[workspace]
members = [
    "service",
    "ncli",
]

[workspace.package]
version = "0.2.4"
edition = "2018"
publish = false

[dependencies]
cherryrgb = { path = "cherryrgb" }
anyhow = "1.0"
structopt = "0.3"
log = "0.4"

[dependencies.simple_logger]
version = "1.13"
default-features = false
features = ["colors"]
