name: Test check-versions reusable action

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version or Tag'     
        type: string
        required: false

jobs:
  test:
    uses: ./.github/workflows/check-versions.yml
    with:
      version: ${{ inputs.version }}
      #tomls: '["Cargo.toml", "cherryrgb/Cargo.toml"]'
      tomls: '[]'

