name: Test check-versions reusable action

on:
  workflow_dispatch:
    inputs:
      refname:
        required: true
        description: 'Version or Tag'     
        type: string
      reftype:
        required: true
        description: 'Type of refname'
        type: choice
        options:
          - tag
          - branch

jobs:
  test:
    uses: ./.github/workflows/check-versions.yml
    with:
      refname: ${{ inputs.refname }}
      reftype: ${{ inputs.reftype }}
      tomls: '["Cargo.toml", "cherryrgb/Cargo.toml"]'

