name: Test check-versions

on:
  workflow_dispatch:
    inputs:
      refname:
        required: true
        description: 'Version or Tag'     
        type: string
      reftype:
        required: true
        description: 'Type of refname'
        type: choice
        options:
          - tag
          - branch

jobs:
  test1:
    uses: ./.github/workflows/check-versions.yml
    with:
      refname: ${{ inputs.refname }}
      reftype: ${{ inputs.reftype }}
      tomls: '["Cargo.toml", "cherryrgb/Cargo.toml"]'

  test2:
    uses: ./.github/workflows/check-versions.yml
    with:
      refname: ${{ inputs.refname }}
      reftype: ${{ inputs.reftype }}
      tomls: '["Cargo-falsch.toml", "cherryrgb/Cargo.toml"]'

  test3:
    uses: ./.github/workflows/check-versions.yml
    with:
      refname: ${{ inputs.refname }}
      reftype: ${{ inputs.reftype }}
      tomls: '["gibsnich", "cherryrgb/Cargo.toml"]'

  test4:
    uses: ./.github/workflows/check-versions.yml
    with:
      refname: ${{ inputs.refname }}
      reftype: ${{ inputs.reftype }}
      tomls: 'fubar'

